### ISSUE TITLE
cover requests

### ISSUE THREAD

**Issue by pb29** [ZephraCloud/Apple-Music-RPC#3]
**__Her (Original Score)__**
**__https://music.apple.com/us/album/her-original-score/1553022037__**
**__Feeding Seahorses by Hand__**
**__https://music.apple.com/us/album/feeding-seahorses-by-hand/1454658392__**
**__Parachutes__**
**__https://music.apple.com/us/album/parachutes/696830354__**
**__A Rush of Blood to the Head__**
**__https://music.apple.com/us/album/a-rush-of-blood-to-the-head/696786871__**
**__O__**
**__https://music.apple.com/us/album/o/41864569__**
**__Freudian__**
**__https://music.apple.com/us/album/freudian/1265893523__**
**__Down to Earth__**
**__https://music.apple.com/us/album/down-to-earth/1481728567__**
**__How Big, How Blue, How Beautiful (Deluxe)__**
**__https://music.apple.com/us/album/how-big-how-blue-how-beautiful-deluxe/1440841106__**
**__Flume__**
**__https://music.apple.com/us/album/flume/1481728929__**
**__Flume (Deluxe Edition)__**
**__https://music.apple.com/us/album/flume-deluxe-edition/1483338723__**
**__Skin__**
**__https://music.apple.com/us/album/skin/1481729150__**
**__Hi This Is Flume (Mixtape)__**
**__https://music.apple.com/us/album/hi-this-is-flume-mixtape/1455360241__**
**__Channel ORANGE__**
**__https://music.apple.com/kr/album/channel-orange/1440760117__**
**__Blonde__**
**__https://music.apple.com/us/album/blonde/1146195596__**
**__Never Trust a Happy Song__**
**__https://music.apple.com/us/album/never-trust-a-happy-song/453792966__**
**__Chewing Cotton Wool - EP__**
**__https://music.apple.com/us/album/chewing-cotton-wool-ep/1525941379__**
**__The OOZ__**
**__https://music.apple.com/us/album/the-ooz/1273304020__**
**__6 Feet Beneath the Moon__**
**__https://music.apple.com/us/album/6-feet-beneath-the-moon/667893470__**
**__Melodrama__**
**__https://music.apple.com/us/album/melodrama/1429662346__**
**__Swimming__**
**__https://music.apple.com/us/album/swimming/1408996052__**
**__Adventure (Deluxe)__**
**__https://music.apple.com/us/album/adventure-deluxe/955824966__**
**__Good Faith__**
**__https://music.apple.com/us/album/good-faith/1485487825__**
**__Nurture__**
**__https://music.apple.com/us/album/nurture/1550626757__**
**__Worlds__**
**__https://music.apple.com/us/album/worlds/1440857923__**
**__In Rainbows__**
**__https://music.apple.com/us/album/in-rainbows/1109714933__**
**__The Bends__**
**__https://music.apple.com/us/album/the-bends/1097862703__**
**__Ritchie Blackmore's Rainbow__**
**__https://music.apple.com/us/album/ritchie-blackmores-rainbow/1440924592__**

How can I requesting Album that name is not english but US apple music have translated title so it could be not find the right cover?
such like this album- KR AM got 비적응, US AM got Nonadaptation
비적응
https://music.apple.com/kr/album/nonadaptation/1499306579
Nonadaptation
https://music.apple.com/us/album/nonadaptation/1499306579
I will write down some of same albums with english and korean title & url each.

Korean Version
**__비적응__**
**__https://music.apple.com/kr/album/nonadaptation/1579381741__**
**__여름깃 - EP__**
**__https://music.apple.com/kr/album/summer-plumage-ep/1450484183__**
**__자유 - Single__**
**__https://music.apple.com/kr/album/jayu-single/1552309669__**

English Version
**__Nonadaptation__**
**__https://music.apple.com/us/album/nonadaptation/1499306579__**
**__Summer Plumage - EP__**
**__https://music.apple.com/us/album/summer-plumage-ep/1450484183__**
**__Jayu - Single__**
**__https://music.apple.com/us/album/jayu-single/1552327274__**

thanks! and.... I hope cover addition work is not each of them by hands....

**Comment by N0chteil** [comment]
Thanks for all the covers! We'll add them soon.

**Comment by N0chteil** [comment]
_We change some things in the cover system_ 950e34c

**Comment by N0chteil** [comment]
Hey @pb29,
as you can see in the [v3.0.0 changelog](https://github.com/ZephraCloud/Apple-Music-RPC/releases/tag/v3.0.0), we've added the ability to display artworks (covers) for every song. This is currently only available for AME, but we will add support for iTunes in the next version!

We hope you still have a good experience with AMRPC and wish you a Happy New Year!
