### ISSUE TITLE
BUG | cmd window spamming

### ISSUE THREAD

**Issue by pb29** [ZephraCloud/Apple-Music-RPC#5]
**Describe the bug**

Discord RPC seems working great with iTunes and also the album covers.
but when while program is running, cmd terminal window keeps spamming me

**To Reproduce**
Just running the program

**Expected behavior**
terminal window spamming

**Screenshots**
![Honeycam 2022-01-01 19-20-40](https://user-images.githubusercontent.com/26969207/147848499-28c3f04a-1ee9-4edb-ad5f-a5788e9c8380.gif)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 21H2 22000.376

**Comment by N0chteil** [comment]
Can you confirm that version [3.1.1](https://github.com/ZephraCloud/Apple-Music-RPC/releases/tag/v3.1.1) fixes this problem?

**Comment by pb29** [comment]
yep, it's solved!
