### ISSUE TITLE
[AMR-7][BUG] High CPU Usage

### ISSUE THREAD

**Issue by exiva** [ZephraCloud/Apple-Music-RPC#8]
## Describe the bug
Application is using a ton of CPU on macOS.

### Steps to reproduce the behavior
Run the application
Open activity monitor, observe it using 80-90% of CPU.

### Expected behavior
App should use next to no CPU.

### Screenshots
<img width="420" alt="Screen Shot 2022-02-13 at 4 41 21 PM" src="https://user-images.githubusercontent.com/56931/153776353-822298ad-63a5-46da-b9dc-1e0b758601f8.png">

### Desktop (please complete the following information):
 - OS: macOS 
 - Version 12.2 x86

## Log file
[main.log](https://github.com/ZephraCloud/Apple-Music-RPC/files/8056728/main.log)

**Comment by N0chteil** [comment]
Hey,
we'll try to fix this problem with the new [Apple-Bridge](https://github.com/ZephraCloud/Apple-Bridge), as the one currently in use has many bugs (such as the high CPU usage you mentioned).
