### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Aviviviviveee** [ZephraCloud/Apple-Music-RPC#9]
![Screenshot 2022-02-16 at 17 20 23](https://user-images.githubusercontent.com/98211163/154309490-a2d0bf2d-7c7e-4693-96f2-a6b7d59da093.png)

I'm on my M1 and this happens

**Comment by N0chteil** [comment]
Hey,
which file did you download?

**Comment by Aviviviviveee** [comment]
![Screenshot 2022-02-16 at 17 23 01](https://user-images.githubusercontent.com/98211163/154311391-defff768-6647-44de-b5d1-14c73298f8be.png)

**Comment by Aviviviviveee** [comment]
i have the same issue as the person within the Apple Discussions link you sent so no it wont do any good

**Comment by N0chteil** [comment]
Take a look at [this](https://appuals.com/damaged-app-cannot-be-opened-on-macos-error/) article. Maybe it will fix the problem

**Comment by N0chteil** [comment]
_No response_
